sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - 10
  - 12
  - node
before_script:
  - yarn bootstrap
script:
  - yarn test
after_success:
  - yarn codecov
env:
  global:
    - FORCE_COLOR=1
    - secure: dHdnulkfL3Es9kaH0JVFwPk5VUeD7fdiMYdNaId09ZTa9mL9BvYcHmeVK5g1ZIm1F0+QmLeJwjO+4dq1yjRz6IFnpbgQSlhIbYjs+8zBc1v+HTZZfB/kFRIqHO0x4nJG8vKVa+Sg5tp0pI7hiCgevsrlvf4Pb6D0Cyx+faSGNrY=
